version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "27017:27017"
    env_file:
      - ./.env.local
    volumes:
      - database:/data/db

volumes:
  database:
